always_rejected: 
  explanation: 'This PR is still work in progress'
  labels: 
    - wip
  title_regex: '(WIP|wip)'
approve_by_comment: true
approve_regex: '^(A|a)pprov|\+1'
author_approval: ignored
reject_regex: '^(R|r)eject|-1'
reject_value: -1
reset_on_push: true
reviewers: 
  name: default
  required: 2
  teams: 
    - trusted
